"""recently added table

Revision ID: 2fbb8ebcb2da
Revises: 494c6d111adf
Create Date: 2015-04-10 16:53:29.188918

"""

# revision identifiers, used by Alembic.
revision = '2fbb8ebcb2da'
down_revision = '494c6d111adf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recently_added', sa.Column('filename', sa.Text(), nullable=True))
    op.add_column('recently_added', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recently_added', 'title')
    op.drop_column('recently_added', 'filename')
    ### end Alembic commands ###
